### ISSUE TITLE
Maestro not communicating to spotify

### ISSUE THREAD

**Issue by zdavis28** [smashingboxes/maestro#2]
I have Maestro install as described in readme and it communicates through slack correctly, but it does not do anything in Spotify.

Example:
when doing /spotbot list, my reply is:
'Currently available playlist:'

When I do /spotbot remove office I get a 'Playlist Removed' response.

I am not sure what information I can provided to assist with this, but I would be happy to provide anything needed.

**Comment by BrandonMathis** [comment]
Does the `help` command work?

You should be able to type `play <spotify_uri>` and the specified song will start playing. It sounds like to be that you have everything hooked up right if you are getting the "Playlist Removed" response

**Comment by zdavis28** [comment]
it does. It looks like I can play a song directly now and I can change volume and everything. I cannot create a playlist though. Does it interface with playlists from spotify or only bot specific ones?

**Comment by zdavis28** [comment]
I got it figure out. Thanks!

**Comment by BrandonMathis** [comment]
Excellent!
