### ISSUE TITLE
README.md needs to be updated

### ISSUE THREAD

**Issue by NoqturnalOne** [smashingboxes/maestro#22]
Readme states to run the following commands in terminal:

```
brew install shpotify

git clone git@github.com:smashingboxes/maestro.git
cd maestro
bundle install
```

Needs to be corrected to:

```
brew install shpotify

git clone https://github.com/smashingboxes/maestro.git
cd maestro
bundle install
```

When using `git clone git@github.com:smashingboxes/maestro.git` terminal returns:

> Permission denied (publickey)
> fatal: Could not read from remote repository.

**Comment by TylerRockwell** [comment]
Thanks for pointing this out. It'll be fixed shortly.

**Comment by TylerRockwell** [comment]
For future reference, you can also clone via `git` urls by adding an [SSH Key](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/) to your GitHub account.
