### ISSUE TITLE
Bundle Command Not Found

### ISSUE THREAD

**Issue by NoqturnalOne** [smashingboxes/maestro#24]
When running `bundle install` during steps detailed in README.md terminal returns: 

`-bash: bundle: command not found`

Please forgive my inexperience but is there a prerequisite install I need to complete before this step? All previous steps detailed in the readme have been completed successfully.

**Comment by woolsox** [comment]
@NoqturnalOne do you have the `bundler` gem installed?

`gem install bundler`

**Comment by TylerRockwell** [comment]
The README assumes that you have a working Ruby development environment setup locally.

**Comment by NoqturnalOne** [comment]
@woolsox @TylerRockwell 

I will need to get bundler set up, then. 

Seems when I use `gem install bundler` with or without `sudo` I'm getting the following error:

> ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
>           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/latest_specs.4.8.gz)

Seems I need to do a bit more reading on the subject. Thanks again.

**Comment by TylerRockwell** [comment]
This seems relevant to the issue you're having: https://stackoverflow.com/questions/19132450/error-installing-bundler

In general, you never want to use `sudo` when installing gems. It'll cause you endless permissions headaches, and if you're finding the need to use `sudo`, then there's likely a configuration issue elsewhere that needs to be resolved. Best of luck!

**Comment by NoqturnalOne** [comment]
For the benefit of anyone reading this in the future, I was able to resolve my issues installing bundler with the following:

Referenced https://rvm.io/rvm/install for steps to install RVM:

Ran `curl -sSL https://get.rvm.io | bash -s stable --ruby` in terminal

Ran `source /Users/%username%/.rvm/scripts/rvm` in terminal

After the above, I was able to run the `gem` command without issues. 

Cheers.
