### ISSUE TITLE
Libspotify depreacated, Application Key not available

### ISSUE THREAD

**Issue by dmnfr** [smashingboxes/maestro#4]
Hi,

Libspotify is deprecated since 2012, and it become complicated to get an application key from spotify.
An alternative could be to use : https://github.com/plietar/librespot , which doesn't need application keys

**Comment by dmnfr** [comment]
Could also switch to https://github.com/TooTallNate/node-spotify-web

**Comment by dkniffin** [comment]
Closing this as a duplicate of #3
